version: "3"
service:
  api:
    image: rafaelcarvalhocaetano/apinewsredis
    ports:
      - "5000:3050"
    links:
      - link-db
  link-db:
    image: tutum/mongodb
    ports:
      -"27017:27017"
      -"28017:28017"
    environment:
      - AUTH=no
    redis:
      image: 'redis'